BK-787 Create bulk items
doofinder/php-doofinder pull request #81
Opened 2022-01-13 14:26 UTC by GLagunilla

BK-787

2022-01-13 16:14 UTC, agutierrezrodriguez requested changes
I think that you want to write "index id" or "index name" or something related.

2022-01-13 16:14 UTC, agutierrezrodriguez commented on src/Management/ManagementClient.php
> +    public function updateItemsInBulk($hashId, $itemId, $params)
same here

2022-01-13 16:14 UTC, agutierrezrodriguez commented on src/Management/ManagementClient.php
> +    public function deleteItemsInBulk($hashId, $itemId, $params)
and same here

2022-01-13 16:21 UTC, GLagunilla commented
Yes, it should be $indexName :man_facepalming:

2022-01-14 08:23 UTC, agutierrezrodriguez approved these changes

2022-01-14 08:39 UTC, vpoten approved these changes

2022-01-14 08:40 UTC, merged